const fs = require('fs');
const path = require('path');

const rarityOrder = ['Normal', 'Rare', 'Epic', 'Legendary'];
const rarityCodes = { Normal: 'NO', Rare: 'RA', Epic: 'EP', Legendary: 'LE' };
const typeCodes = { Attack: 'ATT', Heal: 'HEA', Special: 'SPE', Defense: 'DEF' };
const typeOffsets = {
  Attack: { Normal: 0, Rare: 1, Epic: 2, Legendary: 3 },
  Heal: { Normal: 4, Rare: 5, Epic: 6, Legendary: 7 },
  Special: { Normal: 8, Rare: 9, Epic: 10, Legendary: 11 },
  Defense: { Normal: 12, Rare: 13, Epic: 14, Legendary: 15 },
};

const deepClone = obj => JSON.parse(JSON.stringify(obj));

const effectPresets = {
  A01: {
    group: 'Attack',
    name: '기본 공격',
    effectText: '피해 20',
    keywords: [],
    tags: ['Neutral'],
    vfx: 'atk_basic',
    sfx: 'hit_generic',
    levelCurve: { base: { damage: 20 }, perLevel: { damage: 2 } },
    effects: () => [{ type: 'Damage', value: 20 }],
  },
  A02: {
    group: 'Attack',
    name: '파이어볼',
    effectText: '피해 30, 화상 1중첩 부여',
    keywords: ['Burn'],
    tags: ['Fire'],
    vfx: 'atk_fire',
    sfx: 'hit_fire',
    levelCurve: { base: { damage: 30 }, perLevel: { damage: 3 } },
    effects: () => [
      { type: 'Damage', value: 30 },
      { type: 'ApplyStatus', key: 'Burn', stacks: 1, duration: 2, target: 'enemy' },
    ],
  },
  A03: {
    group: 'Attack',
    name: '화염 폭발',
    effectText: '피해 36, 화상 2중첩, 취약 1중첩(2턴)',
    keywords: ['Burn', 'Vulnerable'],
    tags: ['Fire'],
    vfx: 'atk_fire_aoe',
    sfx: 'explosion_fire',
    levelCurve: { base: { damage: 36 }, perLevel: { damage: 4 } },
    effects: () => [
      { type: 'Damage', value: 36 },
      { type: 'ApplyStatus', key: 'Burn', stacks: 2, duration: 2, target: 'enemy' },
      { type: 'ApplyStatus', key: 'Vulnerable', stacks: 1, duration: 2, target: 'enemy' },
    ],
  },
  A04: {
    group: 'Attack',
    name: '처형',
    effectText: '피해 50, 대상 HP 30% 이하시 +30',
    keywords: ['Conditional'],
    tags: ['Neutral'],
    vfx: 'atk_execute',
    sfx: 'hit_final',
    levelCurve: { base: { damage: 50 }, perLevel: { damage: 5 } },
    effects: () => [
      { type: 'Damage', value: 50 },
      { type: 'Conditional', if: 'targetHp<=30%', then: [{ type: 'Damage', value: 30 }] },
    ],
  },
  A05: {
    group: 'Attack',
    name: '혈월의 일격',
    effectText: '피해 26, 적에게 출혈 2중첩(턴마다 6 피해)',
    keywords: ['Bleed'],
    tags: ['Shadow'],
    vfx: 'atk_bleed',
    sfx: 'slash_heavy',
    levelCurve: { base: { damage: 26 }, perLevel: { damage: 3 } },
    effects: () => [
      { type: 'Damage', value: 26 },
      { type: 'ApplyBleed', stacks: 2, duration: 2, damagePerStack: 6 },
    ],
  },
  A06: {
    group: 'Attack',
    name: '폭풍 연격',
    effectText: '피해 18, 연쇄 피해, 감전 1중첩',
    keywords: ['Shock'],
    tags: ['Lightning'],
    vfx: 'atk_lightning',
    sfx: 'slash_fast',
    levelCurve: { base: { damage: 18 }, perLevel: { damage: 2 } },
    effects: () => [
      { type: 'Damage', value: 18 },
      { type: 'Chain', targets: 2, ratio: 0.6 },
      { type: 'ApplyStatus', key: 'Shock', stacks: 1, duration: 2, target: 'enemy' },
    ],
  },
  A07: {
    group: 'Attack',
    name: '얼음 척살',
    effectText: '피해 24, 적에게 빙결 적용',
    keywords: ['Freeze'],
    tags: ['Ice'],
    vfx: 'atk_ice',
    sfx: 'freeze_snap',
    levelCurve: { base: { damage: 24 }, perLevel: { damage: 3 } },
    effects: () => [
      { type: 'Damage', value: 24 },
      { type: 'ApplyStatus', key: 'Freeze', duration: 1 },
      { type: 'Conditional', if: 'targetStatus=Freeze', then: [{ type: 'Damage', value: 10 }] },
    ],
  },
  A08: {
    group: 'Attack',
    name: '균열 투척',
    effectText: '피해 22, 적의 가드/보호막 15 파괴',
    keywords: ['ArmorBreak'],
    tags: ['Metal'],
    vfx: 'atk_shatter',
    sfx: 'armor_break',
    levelCurve: { base: { damage: 22 }, perLevel: { damage: 3 } },
    effects: () => [
      { type: 'Damage', value: 22 },
      { type: 'ArmorBreak', guard: 15, shield: 15 },
    ],
  },
  A09: {
    group: 'Attack',
    name: '룬식 충격',
    effectText: '피해 20, 취약 1중첩, 에너지 +0.5',
    keywords: ['Vulnerable'],
    tags: ['Arcane'],
    vfx: 'atk_arcane',
    sfx: 'magic_hit',
    levelCurve: { base: { damage: 20 }, perLevel: { damage: 2 } },
    effects: () => [
      { type: 'Damage', value: 20 },
      { type: 'ApplyStatus', key: 'Vulnerable', stacks: 1, duration: 2, value: 20 },
      { type: 'GainAction', value: 0.5 },
    ],
  },
  A10: {
    group: 'Attack',
    name: '심연 파동',
    effectText: '피해 16 ×4, 피해의 50% 흡혈',
    keywords: ['Leech'],
    tags: ['Shadow'],
    vfx: 'atk_shadow',
    sfx: 'shadow_slash',
    levelCurve: { base: { damage: 16 }, perLevel: { damage: 2 } },
    effects: () => [
      { type: 'Damage', value: 16, hits: 4, lifestealRatio: 0.5 },
    ],
  },
  A11: {
    group: 'Attack',
    name: '성광 일섬',
    effectText: '피해 28, 자신 정화, 1턴간 공격력 +10%',
    keywords: ['Cleanse', 'Buff'],
    tags: ['Light'],
    vfx: 'atk_light',
    sfx: 'holy_slash',
    levelCurve: { base: { damage: 28 }, perLevel: { damage: 3 } },
    effects: () => [
      { type: 'Damage', value: 28 },
      { type: 'Cleanse', maxStacks: 2 },
      { type: 'Buff', stat: 'attack', value: 10, duration: 1 },
    ],
  },
  A12: {
    group: 'Attack',
    name: '용연 연격',
    effectText: '피해 15, 다음 공격 카드 1회 추가 사용, 체력 5 회복',
    keywords: ['Duplicate'],
    tags: ['Dragon'],
    vfx: 'atk_dragon',
    sfx: 'dragon_slash',
    levelCurve: { base: { damage: 15 }, perLevel: { damage: 2 } },
    effects: () => [
      { type: 'Damage', value: 15 },
      { type: 'DuplicateNext', typeFilter: 'Attack', times: 1 },
      { type: 'Heal', value: 5 },
    ],
  },
  A13: {
    group: 'Attack',
    name: '자음 포화',
    effectText: '피해 30, 감전 2중첩, 다음 턴 에너지 +1',
    keywords: ['Shock', 'Tempo'],
    tags: ['Lightning'],
    vfx: 'atk_lightning_burst',
    sfx: 'bolt_chain',
    levelCurve: { base: { damage: 30 }, perLevel: { damage: 3 } },
    effects: () => [
      { type: 'Damage', value: 30 },
      { type: 'ApplyStatus', key: 'Shock', stacks: 2, duration: 2 },
      { type: 'TempoBoost', amount: 1, turns: 1 },
    ],
  },
  A14: {
    group: 'Attack',
    name: '유리령 사격',
    effectText: '피해 18, 회피 1회, 카드 1장 드로우',
    keywords: ['Evasion', 'Draw'],
    tags: ['Shadow'],
    vfx: 'atk_ghost',
    sfx: 'arrow_whisper',
    levelCurve: { base: { damage: 18 }, perLevel: { damage: 2 } },
    effects: () => [
      { type: 'Damage', value: 18 },
      { type: 'Evasion', charges: 1, duration: 1 },
      { type: 'Draw', value: 1 },
    ],
  },
  A15: {
    group: 'Attack',
    name: '연성 폭연',
    effectText: '피해 22, 화상 1중첩, 취약 1중첩',
    keywords: ['Burn', 'Vulnerable'],
    tags: ['Fire'],
    vfx: 'atk_forge',
    sfx: 'blast_fire',
    levelCurve: { base: { damage: 22 }, perLevel: { damage: 3 } },
    effects: () => [
      { type: 'Damage', value: 22 },
      { type: 'ApplyStatus', key: 'Burn', stacks: 1, duration: 2 },
      { type: 'ApplyStatus', key: 'Vulnerable', stacks: 1, duration: 1, value: 20, target: 'player' },
    ],
  },
  D01: {
    group: 'Defense',
    name: '방패 올리기',
    effectText: '보호막 20 (1턴)',
    keywords: ['Shield'],
    tags: ['Neutral'],
    vfx: 'shield',
    sfx: 'block_shield',
    levelCurve: { base: { shield: 20 }, perLevel: { shield: 2 } },
    effects: () => [{ type: 'Shield', value: 20, duration: 1 }],
  },
  D02: {
    group: 'Defense',
    name: '받아치기',
    effectText: '반격 20 (1턴)',
    keywords: ['Counter'],
    tags: ['Neutral'],
    vfx: 'counter',
    sfx: 'clang',
    levelCurve: {},
    effects: () => [{ type: 'Counter', value: 20, duration: 1 }],
  },
  D03: {
    group: 'Defense',
    name: '무효의 벽',
    effectText: '상대 카드 1회 무효화',
    keywords: ['Nullify'],
    tags: ['Neutral'],
    vfx: 'null_wall',
    sfx: 'whoosh_cancel',
    levelCurve: {},
    effects: () => [{ type: 'Nullify', times: 1 }],
  },
  D04: {
    group: 'Defense',
    name: '성스러운 보호',
    effectText: '보호막 40 (2턴), 화상 면역 1턴',
    keywords: ['Shield', 'Immune'],
    tags: ['Light'],
    vfx: 'aegis',
    sfx: 'shield_holy',
    levelCurve: { base: { shield: 40 }, perLevel: { shield: 4 } },
    effects: () => [
      { type: 'Shield', value: 40, duration: 2 },
      { type: 'Immune', keywords: ['Burn'], duration: 1 },
    ],
  },
  D05: {
    group: 'Defense',
    name: '반응 장갑 전개',
    effectText: '반응 장갑 2회, 반격 35%, 보호막 전환 25%',
    keywords: ['Reactive'],
    tags: ['Metal'],
    vfx: 'def_reactive',
    sfx: 'armor_charge',
    levelCurve: {},
    effects: () => [
      { type: 'ReactiveArmor', charges: 2, reflectRatio: 0.35, shieldRatio: 0.25, duration: 2 },
      { type: 'Guard', value: 8, duration: 2 },
    ],
  },
  D06: {
    group: 'Defense',
    name: '결빙 장막',
    effectText: '보호막 18 (2턴), 공격자를 빙결',
    keywords: ['Freeze'],
    tags: ['Ice'],
    vfx: 'barrier_ice',
    sfx: 'ice_shield',
    levelCurve: { base: { shield: 18 }, perLevel: { shield: 3 } },
    effects: () => [
      { type: 'Shield', value: 18, duration: 2 },
      { type: 'OnHitStatus', status: { key: 'Freeze', duration: 1 }, duration: 2 },
    ],
  },
  D07: {
    group: 'Defense',
    name: '천벌 결계',
    effectText: '보호막 25 (2턴), 공격자 감전, 다음 턴 에너지 +1',
    keywords: ['Shock', 'Tempo'],
    tags: ['Lightning'],
    vfx: 'barrier_thunder',
    sfx: 'shield_static',
    levelCurve: { base: { shield: 25 }, perLevel: { shield: 3 } },
    effects: () => [
      { type: 'Shield', value: 25, duration: 2 },
      { type: 'OnHitStatus', status: { key: 'Shock', stacks: 1, duration: 2 }, duration: 2 },
      { type: 'TempoBoost', amount: 1, turns: 1 },
    ],
  },
  D08: {
    group: 'Defense',
    name: '그림자 회피술',
    effectText: '회피 2회, 반격 12 (1턴)',
    keywords: ['Evasion', 'Counter'],
    tags: ['Shadow'],
    vfx: 'evasion',
    sfx: 'dash',
    levelCurve: {},
    effects: () => [
      { type: 'Evasion', charges: 2, duration: 1 },
      { type: 'Counter', value: 12, duration: 1 },
    ],
  },
  D09: {
    group: 'Defense',
    name: '철벽 방진',
    effectText: '가드 18 (2턴), 다음 턴 에너지 +1',
    keywords: ['Guard', 'Tempo'],
    tags: ['Metal'],
    vfx: 'guard_wall',
    sfx: 'shield_block',
    levelCurve: {},
    effects: () => [
      { type: 'Guard', value: 18, duration: 2 },
      { type: 'GainAction', value: 1, delayed: true, delayTurns: 1 },
    ],
  },
  D10: {
    group: 'Defense',
    name: '성역 구축',
    effectText: '보호막 30 (3턴), 매턴 회복 5',
    keywords: ['Shield', 'Regen'],
    tags: ['Light'],
    vfx: 'holy_barrier',
    sfx: 'holy_aura',
    levelCurve: { base: { shield: 30 }, perLevel: { shield: 3 } },
    effects: () => [
      { type: 'Shield', value: 30, duration: 3 },
      { type: 'Regen', value: 5, duration: 3 },
    ],
  },
  D11: {
    group: 'Defense',
    name: '속박 덫',
    effectText: '가드 10 (2턴), 적에게 구속 1턴',
    keywords: ['Guard', 'Root'],
    tags: ['Trap'],
    vfx: 'trap_root',
    sfx: 'trap_snap',
    levelCurve: {},
    effects: () => [
      { type: 'Guard', value: 10, duration: 2 },
      { type: 'ApplyStatus', key: 'Root', duration: 1, target: 'enemy' },
    ],
  },
  D12: {
    group: 'Defense',
    name: '마력 역류',
    effectText: '무효화 1회, 성공 시 에너지 +1',
    keywords: ['Nullify'],
    tags: ['Arcane'],
    vfx: 'null_reflect',
    sfx: 'mana_wave',
    levelCurve: {},
    effects: () => [
      { type: 'Nullify', times: 1 },
      { type: 'ConditionalTrigger', event: 'nullify', effects: [{ type: 'GainAction', value: 1 }] },
    ],
  },
  D13: {
    group: 'Defense',
    name: '지각 단층',
    effectText: '보호막 20 (2턴), 공격자에게 취약 부여',
    keywords: ['Shield', 'Vulnerable'],
    tags: ['Earth'],
    vfx: 'barrier_earth',
    sfx: 'rumble',
    levelCurve: { base: { shield: 20 }, perLevel: { shield: 3 } },
    effects: () => [
      { type: 'Shield', value: 20, duration: 2 },
      { type: 'OnHitStatus', status: { key: 'Vulnerable', stacks: 1, duration: 2, value: 20 }, duration: 2 },
    ],
  },
  D14: {
    group: 'Defense',
    name: '회오리 방출',
    effectText: '회피 1회, 피해 16, 적에게 쇼크 1중첩',
    keywords: ['Evasion', 'Damage', 'Shock'],
    tags: ['Wind'],
    vfx: 'tornado',
    sfx: 'wind_slice',
    levelCurve: {},
    effects: () => [
      { type: 'Evasion', charges: 1, duration: 1 },
      { type: 'Damage', value: 16 },
      { type: 'ApplyStatus', key: 'Shock', stacks: 1, duration: 2 },
    ],
  },
  H01: {
    group: 'Heal',
    name: '기본 회복',
    effectText: '체력 20 회복',
    keywords: [],
    tags: ['Neutral'],
    vfx: 'heal_basic',
    sfx: 'heal_soft',
    levelCurve: { base: { heal: 20 }, perLevel: { heal: 2 } },
    effects: () => [{ type: 'Heal', value: 20 }],
  },
  H02: {
    group: 'Heal',
    name: '강한 회복',
    effectText: '체력 40 회복',
    keywords: [],
    tags: ['Neutral'],
    vfx: 'heal_strong',
    sfx: 'heal_soft',
    levelCurve: { base: { heal: 40 }, perLevel: { heal: 4 } },
    effects: () => [{ type: 'Heal', value: 40 }],
  },
  H03: {
    group: 'Heal',
    name: '완전 회복',
    effectText: '체력 60 회복',
    keywords: [],
    tags: ['Neutral'],
    vfx: 'heal_full',
    sfx: 'heal_soft',
    levelCurve: { base: { heal: 60 }, perLevel: { heal: 5 } },
    effects: () => [{ type: 'Heal', value: 60 }],
  },
  H04: {
    group: 'Heal',
    name: '축복',
    effectText: '체력 60 회복, 2턴간 공격력 +20%',
    keywords: ['Buff'],
    tags: ['Light'],
    vfx: 'bless',
    sfx: 'bless',
    levelCurve: { base: { heal: 60 }, perLevel: { heal: 5 } },
    effects: () => [
      { type: 'Heal', value: 60 },
      { type: 'Buff', stat: 'attack', value: 20, duration: 2 },
    ],
  },
  H05: {
    group: 'Heal',
    name: '빛의 넘침',
    effectText: '회복 24, 초과분 보호막, 2턴간 매턴 6 회복',
    keywords: ['Shield', 'Regen'],
    tags: ['Light'],
    vfx: 'heal_overflow',
    sfx: 'heal_glow',
    levelCurve: { base: { heal: 24 }, perLevel: { heal: 3 } },
    effects: () => [
      { type: 'Heal', value: 24, overflowToShield: true },
      { type: 'Regen', value: 6, duration: 2 },
    ],
  },
  H06: {
    group: 'Heal',
    name: '정화의 숨결',
    effectText: '체력 25 회복, 자신에게서 상태이상 3개 해제',
    keywords: ['Cleanse'],
    tags: ['Holy'],
    vfx: 'cleanse',
    sfx: 'cleanse',
    levelCurve: { base: { heal: 25 }, perLevel: { heal: 3 } },
    effects: () => [
      { type: 'Heal', value: 25 },
      { type: 'Cleanse', maxStacks: 3 },
    ],
  },
  H07: {
    group: 'Heal',
    name: '생명 전이',
    effectText: '체력 25 회복, 보호막 15 부여',
    keywords: ['Shield'],
    tags: ['Life'],
    vfx: 'life_transfer',
    sfx: 'heal_transfer',
    levelCurve: { base: { heal: 25 }, perLevel: { heal: 3 } },
    effects: () => [
      { type: 'Heal', value: 25 },
      { type: 'Shield', value: 15, duration: 2 },
    ],
  },
  H08: {
    group: 'Heal',
    name: '월광 재생',
    effectText: '체력 18 회복, 매턴 8 회복, 적에게 출혈 1중첩',
    keywords: ['Regen', 'Bleed'],
    tags: ['Shadow'],
    vfx: 'heal_shadow',
    sfx: 'heal_dark',
    levelCurve: { base: { heal: 18 }, perLevel: { heal: 3 } },
    effects: () => [
      { type: 'Heal', value: 18 },
      { type: 'Regen', value: 8, duration: 3 },
      { type: 'ApplyBleed', stacks: 1, duration: 2, damagePerStack: 5 },
    ],
  },
  H09: {
    group: 'Heal',
    name: '불굴의 맹세',
    effectText: '체력 20 회복, 가드 12, 반격 15',
    keywords: ['Guard', 'Counter'],
    tags: ['Valor'],
    vfx: 'heal_guard',
    sfx: 'shield_impact',
    levelCurve: { base: { heal: 20 }, perLevel: { heal: 2 } },
    effects: () => [
      { type: 'Heal', value: 20 },
      { type: 'Guard', value: 12, duration: 2 },
      { type: 'Counter', value: 15, duration: 1 },
    ],
  },
  H10: {
    group: 'Heal',
    name: '시간 회귀',
    effectText: '체력 30 회복, 지난 턴 피해의 30% 복구',
    keywords: ['UndoDamage'],
    tags: ['Time'],
    vfx: 'heal_time',
    sfx: 'time_rewind',
    levelCurve: { base: { heal: 30 }, perLevel: { heal: 3 } },
    effects: () => [
      { type: 'Heal', value: 30 },
      { type: 'UndoDamage', percent: 30, target: 'player' },
    ],
  },
  H11: {
    group: 'Heal',
    name: '연금 촉진',
    effectText: '체력 18 회복, 에너지 +1, 2턴간 매턴 4 회복',
    keywords: ['Heal', 'Tempo', 'Regen'],
    tags: ['Alchemy'],
    vfx: 'heal_alchemy',
    sfx: 'heal_soft',
    levelCurve: { base: { heal: 18 }, perLevel: { heal: 2 } },
    effects: () => [
      { type: 'Heal', value: 18 },
      { type: 'Regen', value: 4, duration: 2 },
      { type: 'GainAction', value: 1 },
    ],
  },
  H12: {
    group: 'Heal',
    name: '천위 강림',
    effectText: '체력 35 회복, 화상/감전 면역 1턴, 우선권 +1',
    keywords: ['Immune', 'Priority'],
    tags: ['Holy'],
    vfx: 'heal_angelic',
    sfx: 'angel',
    levelCurve: { base: { heal: 35 }, perLevel: { heal: 3 } },
    effects: () => [
      { type: 'Heal', value: 35 },
      { type: 'Immune', keywords: ['Burn', 'Shock'], duration: 1 },
      { type: 'PriorityBoost', value: 1, duration: 1 },
    ],
  },
  H13: {
    group: 'Heal',
    name: '그림자 봉합',
    effectText: '체력 18 회복, 회피 1회, 다음 방어 카드 복제',
    keywords: ['Evasion', 'Duplicate'],
    tags: ['Shadow'],
    vfx: 'heal_shadow_stitch',
    sfx: 'heal_dark',
    levelCurve: { base: { heal: 18 }, perLevel: { heal: 2 } },
    effects: () => [
      { type: 'Heal', value: 18 },
      { type: 'Evasion', charges: 1, duration: 1 },
      { type: 'DuplicateNext', typeFilter: 'Defense', times: 1 },
    ],
  },
  S01: {
    group: 'Special',
    name: '추가 드로우',
    effectText: '카드 2장 드로우',
    keywords: ['Draw'],
    tags: ['Neutral'],
    vfx: 'draw',
    sfx: 'paper',
    levelCurve: {},
    effects: () => [{ type: 'Draw', value: 2 }],
  },
  S02: {
    group: 'Special',
    name: '행동력 증가',
    effectText: '에너지 +2',
    keywords: ['Tempo'],
    tags: ['Neutral'],
    vfx: 'ap_up',
    sfx: 'tick',
    levelCurve: {},
    effects: () => [{ type: 'GainAction', value: 2 }],
  },
  S03: {
    group: 'Special',
    name: '더블캐스트',
    effectText: '다음 공격 카드 1회 추가 사용',
    keywords: ['Duplicate'],
    tags: ['Arcane'],
    vfx: 'doublecast',
    sfx: 'cast_chime',
    levelCurve: {},
    effects: () => [{ type: 'DuplicateNext', typeFilter: 'Attack', times: 1 }],
  },
  S04: {
    group: 'Special',
    name: '복제',
    effectText: '덱에서 공격 카드 1장을 손패로',
    keywords: ['Copy'],
    tags: ['Arcane'],
    vfx: 'copy',
    sfx: 'cast_chime',
    levelCurve: {},
    effects: () => [{ type: 'CopyCard', from: 'deck', filter: 'type:Attack', to: 'hand' }],
  },
  S05: {
    group: 'Special',
    name: '전술 시계',
    effectText: '다음 2턴 동안 에너지 +2, 카드 1장 드로우',
    keywords: ['Tempo', 'Draw'],
    tags: ['Tactical'],
    vfx: 'spc_tempo',
    sfx: 'clock_twist',
    levelCurve: {},
    effects: () => [
      { type: 'TempoBoost', amount: 2, turns: 2 },
      { type: 'Draw', value: 1 },
    ],
  },
  S06: {
    group: 'Special',
    name: '원소 전환',
    effectText: '원소 변환, 피해 15',
    keywords: ['ElementShift'],
    tags: ['Element'],
    vfx: 'element_shift',
    sfx: 'magic_shift',
    levelCurve: { base: { damage: 15 }, perLevel: { damage: 2 } },
    effects: () => [
      { type: 'ElementShift', from: 'Fire', to: 'Lightning', duration: 2 },
      { type: 'Damage', value: 15 },
    ],
  },
  S07: {
    group: 'Special',
    name: '감응 증폭',
    effectText: '적 전체 감전 1중첩, 감전 상태면 에너지 +1',
    keywords: ['Shock', 'Tempo'],
    tags: ['Lightning'],
    vfx: 'shock_wave',
    sfx: 'electric_pop',
    levelCurve: {},
    effects: () => [
      { type: 'ApplyStatus', key: 'Shock', stacks: 1, duration: 2, chance: 100, target: 'enemy' },
      { type: 'Conditional', if: 'targetStatus=Shock', then: [{ type: 'GainAction', value: 1 }] },
    ],
  },
  S08: {
    group: 'Special',
    name: '빙정 봉인',
    effectText: '적에게 빙결, 다음 공격 무효',
    keywords: ['Freeze', 'Nullify'],
    tags: ['Ice'],
    vfx: 'ice_bind',
    sfx: 'freeze_snap',
    levelCurve: {},
    effects: () => [
      { type: 'ApplyStatus', key: 'Freeze', duration: 1, target: 'enemy' },
      { type: 'Nullify', times: 1 },
    ],
  },
  S09: {
    group: 'Special',
    name: '혼령 소환',
    effectText: '공격력 12, 체력 20의 혼령을 2턴 소환',
    keywords: ['Summon'],
    tags: ['Spirit'],
    vfx: 'summon_wraith',
    sfx: 'spirit',
    levelCurve: {},
    effects: () => [{ type: 'Summon', id: 'wraith', attack: 12, hp: 20, duration: 2 }],
  },
  S10: {
    group: 'Special',
    name: '사령 개시',
    effectText: '체력 0이 되면 20으로 부활, 적에게 출혈 2중첩',
    keywords: ['Revive', 'Bleed'],
    tags: ['Necro'],
    vfx: 'revive_dark',
    sfx: 'revive',
    levelCurve: {},
    effects: () => [
      { type: 'Revive', value: 20, chance: 100 },
      { type: 'ApplyBleed', stacks: 2, duration: 2, damagePerStack: 5 },
    ],
  },
  S11: {
    group: 'Special',
    name: '오라 공진',
    effectText: '2턴간 공격 +15%, 속도 +10, 카드 1장 드로우',
    keywords: ['Buff', 'Draw'],
    tags: ['Aura'],
    vfx: 'aura_resonate',
    sfx: 'magic',
    levelCurve: {},
    effects: () => [
      { type: 'Buff', stat: 'attack', value: 15, duration: 2 },
      { type: 'Buff', stat: 'speed', value: 10, duration: 2 },
      { type: 'Draw', value: 1 },
    ],
  },
  S12: {
    group: 'Special',
    name: '기계 과부하',
    effectText: '에너지 +1, 피해 16, 자신에게 취약 1중첩',
    keywords: ['Tempo', 'Damage'],
    tags: ['Metal'],
    vfx: 'overload',
    sfx: 'metal_overload',
    levelCurve: { base: { damage: 16 }, perLevel: { damage: 2 } },
    effects: () => [
      { type: 'GainAction', value: 1 },
      { type: 'Damage', value: 16 },
      { type: 'ApplyStatus', key: 'Vulnerable', stacks: 1, duration: 1, value: 20 },
    ],
  },
  S13: {
    group: 'Special',
    name: '미러 폴드',
    effectText: '상대 손패에서 코스트가 가장 낮은 카드 1장 훔침',
    keywords: ['Steal'],
    tags: ['Mirror'],
    vfx: 'mirror',
    sfx: 'mirror_woosh',
    levelCurve: {},
    effects: () => [{ type: 'StealCard', from: 'opponentHand', count: 1, filter: 'lowestCost' }],
  },
  S14: {
    group: 'Special',
    name: '시간 정지',
    effectText: '에너지 +2, 40% 확률로 적 턴 스킵',
    keywords: ['Tempo', 'TurnSkip'],
    tags: ['Time'],
    vfx: 'time_stop',
    sfx: 'time_stop',
    levelCurve: {},
    effects: () => [
      { type: 'GainAction', value: 2 },
      { type: 'TurnSkip', chance: 40 },
    ],
  },
  S15: {
    group: 'Special',
    name: '은빛 성가',
    effectText: '팀 전원 매턴 회복 5 (3턴), 상태 2개 정화',
    keywords: ['Regen', 'Cleanse'],
    tags: ['Choir'],
    vfx: 'song',
    sfx: 'choir',
    levelCurve: {},
    effects: () => [
      { type: 'Regen', value: 5, duration: 3 },
      { type: 'Cleanse', maxStacks: 2 },
    ],
  },
  S16: {
    group: 'Special',
    name: '전술 리사이클',
    effectText: '카드 2장 드로우, 다음 턴 에너지 +1',
    keywords: ['Draw', 'Tempo'],
    tags: ['Tactical'],
    vfx: 'recycle',
    sfx: 'shuffle',
    levelCurve: {},
    effects: () => [
      { type: 'Draw', value: 2 },
      { type: 'GainAction', value: 1, delayed: true, delayTurns: 1 },
    ],
  },
  S17: {
    group: 'Special',
    name: '그림자 각인',
    effectText: '적에게 표식 1중첩 (3턴간 피해 +20%)',
    keywords: ['Mark'],
    tags: ['Shadow'],
    vfx: 'mark',
    sfx: 'mark_dagger',
    levelCurve: {},
    effects: () => [{ type: 'ApplyStatus', key: 'Mark', stacks: 1, duration: 3, value: 20, target: 'enemy' }],
  },
  S18: {
    group: 'Special',
    name: '빛의 선언',
    effectText: '2턴간 화상/출혈/감전 면역, 에너지 +1',
    keywords: ['Immune', 'Tempo'],
    tags: ['Light'],
    vfx: 'holy_declare',
    sfx: 'holy_aura',
    levelCurve: {},
    effects: () => [
      { type: 'Immune', keywords: ['Burn', 'Bleed', 'Shock'], duration: 2 },
      { type: 'GainAction', value: 1 },
    ],
  },
  S19: {
    group: 'Special',
    name: '황혼 선포',
    effectText: '피해 12, 화상/출혈 1중첩 부여',
    keywords: ['Burn', 'Bleed'],
    tags: ['Twilight'],
    vfx: 'twilight',
    sfx: 'dark_blast',
    levelCurve: { base: { damage: 12 }, perLevel: { damage: 2 } },
    effects: () => [
      { type: 'Damage', value: 12 },
      { type: 'ApplyStatus', key: 'Burn', stacks: 1, duration: 2 },
      { type: 'ApplyBleed', stacks: 1, duration: 2, damagePerStack: 4 },
    ],
  },
  S20: {
    group: 'Special',
    name: '합금 가속기',
    effectText: '다음 3턴 동안 에너지 +1, 보호막 10 (3턴)',
    keywords: ['Tempo', 'Shield'],
    tags: ['Metal'],
    vfx: 'engine',
    sfx: 'gear',
    levelCurve: {},
    effects: () => [
      { type: 'TempoBoost', amount: 1, turns: 3 },
      { type: 'Shield', value: 10, duration: 3 },
      { type: 'GainAction', value: 1, delayed: true, delayTurns: 1 },
    ],
  },
};

const characters = [
  {
    key: 'ARIANA',
    display: '아리아나',
    theme: 'Arcane',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A01', cost: 1 },
        { rarity: 'Rare', preset: 'A15', cost: 2 },
        { rarity: 'Epic', preset: 'A03', cost: 3 },
        { rarity: 'Legendary', preset: 'A11', cost: 3 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H01', cost: 1 },
        { rarity: 'Rare', preset: 'H06', cost: 2 },
        { rarity: 'Epic', preset: 'H11', cost: 3 },
        { rarity: 'Legendary', preset: 'H12', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S01', cost: 1 },
        { rarity: 'Rare', preset: 'S06', cost: 2 },
        { rarity: 'Epic', preset: 'S11', cost: 3 },
        { rarity: 'Legendary', preset: 'S08', cost: 3 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D01', cost: 1 },
        { rarity: 'Rare', preset: 'D08', cost: 2 },
        { rarity: 'Epic', preset: 'D12', cost: 3 },
        { rarity: 'Legendary', preset: 'D10', cost: 4 },
      ],
    },
  },
  {
    key: 'DARIUS',
    display: '다리우스',
    theme: 'Shadow',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A04', cost: 2 },
        { rarity: 'Rare', preset: 'A05', cost: 2 },
        { rarity: 'Epic', preset: 'A10', cost: 3 },
        { rarity: 'Legendary', preset: 'A13', cost: 3 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H02', cost: 2 },
        { rarity: 'Rare', preset: 'H08', cost: 2 },
        { rarity: 'Epic', preset: 'H07', cost: 3 },
        { rarity: 'Legendary', preset: 'H09', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S05', cost: 2 },
        { rarity: 'Rare', preset: 'S07', cost: 2 },
        { rarity: 'Epic', preset: 'S10', cost: 4 },
        { rarity: 'Legendary', preset: 'S17', cost: 3 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D02', cost: 2 },
        { rarity: 'Rare', preset: 'D05', cost: 3 },
        { rarity: 'Epic', preset: 'D13', cost: 3 },
        { rarity: 'Legendary', preset: 'D14', cost: 4 },
      ],
    },
  },
  {
    key: 'ELDER',
    display: '엘더',
    theme: 'Lightning',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A06', cost: 2 },
        { rarity: 'Rare', preset: 'A03', cost: 3 },
        { rarity: 'Epic', preset: 'A09', cost: 3 },
        { rarity: 'Legendary', preset: 'A14', cost: 3 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H01', cost: 1 },
        { rarity: 'Rare', preset: 'H03', cost: 2 },
        { rarity: 'Epic', preset: 'H10', cost: 3 },
        { rarity: 'Legendary', preset: 'H05', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S01', cost: 1 },
        { rarity: 'Rare', preset: 'S02', cost: 1 },
        { rarity: 'Epic', preset: 'S07', cost: 2 },
        { rarity: 'Legendary', preset: 'S14', cost: 4 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D01', cost: 1 },
        { rarity: 'Rare', preset: 'D07', cost: 2 },
        { rarity: 'Epic', preset: 'D06', cost: 3 },
        { rarity: 'Legendary', preset: 'D10', cost: 4 },
      ],
    },
  },
  {
    key: 'ELENA',
    display: '엘레나',
    theme: 'Ice',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A07', cost: 2 },
        { rarity: 'Rare', preset: 'A02', cost: 2 },
        { rarity: 'Epic', preset: 'A06', cost: 3 },
        { rarity: 'Legendary', preset: 'A12', cost: 3 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H02', cost: 2 },
        { rarity: 'Rare', preset: 'H06', cost: 2 },
        { rarity: 'Epic', preset: 'H05', cost: 3 },
        { rarity: 'Legendary', preset: 'H12', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S03', cost: 2 },
        { rarity: 'Rare', preset: 'S08', cost: 3 },
        { rarity: 'Epic', preset: 'S05', cost: 3 },
        { rarity: 'Legendary', preset: 'S15', cost: 4 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D01', cost: 1 },
        { rarity: 'Rare', preset: 'D06', cost: 2 },
        { rarity: 'Epic', preset: 'D03', cost: 3 },
        { rarity: 'Legendary', preset: 'D04', cost: 4 },
      ],
    },
  },
  {
    key: 'GAREN',
    display: '가렌',
    theme: 'Valor',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A01', cost: 1 },
        { rarity: 'Rare', preset: 'A08', cost: 2 },
        { rarity: 'Epic', preset: 'A13', cost: 3 },
        { rarity: 'Legendary', preset: 'A04', cost: 4 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H01', cost: 1 },
        { rarity: 'Rare', preset: 'H09', cost: 2 },
        { rarity: 'Epic', preset: 'H02', cost: 3 },
        { rarity: 'Legendary', preset: 'H04', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S02', cost: 1 },
        { rarity: 'Rare', preset: 'S16', cost: 2 },
        { rarity: 'Epic', preset: 'S12', cost: 3 },
        { rarity: 'Legendary', preset: 'S18', cost: 4 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D02', cost: 2 },
        { rarity: 'Rare', preset: 'D09', cost: 3 },
        { rarity: 'Epic', preset: 'D01', cost: 2 },
        { rarity: 'Legendary', preset: 'D05', cost: 4 },
      ],
    },
  },
  {
    key: 'IRIS',
    display: '아이리스',
    theme: 'Light',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A02', cost: 2 },
        { rarity: 'Rare', preset: 'A11', cost: 3 },
        { rarity: 'Epic', preset: 'A05', cost: 3 },
        { rarity: 'Legendary', preset: 'A15', cost: 3 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H01', cost: 1 },
        { rarity: 'Rare', preset: 'H05', cost: 2 },
        { rarity: 'Epic', preset: 'H06', cost: 3 },
        { rarity: 'Legendary', preset: 'H12', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S01', cost: 1 },
        { rarity: 'Rare', preset: 'S11', cost: 2 },
        { rarity: 'Epic', preset: 'S15', cost: 3 },
        { rarity: 'Legendary', preset: 'S18', cost: 4 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D01', cost: 1 },
        { rarity: 'Rare', preset: 'D04', cost: 3 },
        { rarity: 'Epic', preset: 'D10', cost: 3 },
        { rarity: 'Legendary', preset: 'D07', cost: 4 },
      ],
    },
  },
  {
    key: 'KAI',
    display: '카이',
    theme: 'Storm',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A06', cost: 2 },
        { rarity: 'Rare', preset: 'A13', cost: 3 },
        { rarity: 'Epic', preset: 'A09', cost: 3 },
        { rarity: 'Legendary', preset: 'A10', cost: 4 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H02', cost: 2 },
        { rarity: 'Rare', preset: 'H10', cost: 3 },
        { rarity: 'Epic', preset: 'H11', cost: 3 },
        { rarity: 'Legendary', preset: 'H08', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S02', cost: 1 },
        { rarity: 'Rare', preset: 'S07', cost: 2 },
        { rarity: 'Epic', preset: 'S14', cost: 4 },
        { rarity: 'Legendary', preset: 'S05', cost: 3 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D02', cost: 2 },
        { rarity: 'Rare', preset: 'D07', cost: 3 },
        { rarity: 'Epic', preset: 'D05', cost: 3 },
        { rarity: 'Legendary', preset: 'D14', cost: 4 },
      ],
    },
  },
  {
    key: 'LEON',
    display: '레온',
    theme: 'Valor',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A01', cost: 1 },
        { rarity: 'Rare', preset: 'A14', cost: 2 },
        { rarity: 'Epic', preset: 'A08', cost: 3 },
        { rarity: 'Legendary', preset: 'A12', cost: 3 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H01', cost: 1 },
        { rarity: 'Rare', preset: 'H09', cost: 2 },
        { rarity: 'Epic', preset: 'H13', cost: 3 },
        { rarity: 'Legendary', preset: 'H04', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S02', cost: 1 },
        { rarity: 'Rare', preset: 'S16', cost: 2 },
        { rarity: 'Epic', preset: 'S03', cost: 3 },
        { rarity: 'Legendary', preset: 'S19', cost: 4 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D01', cost: 1 },
        { rarity: 'Rare', preset: 'D09', cost: 2 },
        { rarity: 'Epic', preset: 'D13', cost: 3 },
        { rarity: 'Legendary', preset: 'D04', cost: 4 },
      ],
    },
  },
  {
    key: 'LUCIAN',
    display: '루시안',
    theme: 'Metal',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A08', cost: 2 },
        { rarity: 'Rare', preset: 'A05', cost: 2 },
        { rarity: 'Epic', preset: 'A03', cost: 3 },
        { rarity: 'Legendary', preset: 'A04', cost: 4 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H02', cost: 2 },
        { rarity: 'Rare', preset: 'H07', cost: 2 },
        { rarity: 'Epic', preset: 'H05', cost: 3 },
        { rarity: 'Legendary', preset: 'H12', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S01', cost: 1 },
        { rarity: 'Rare', preset: 'S12', cost: 2 },
        { rarity: 'Epic', preset: 'S20', cost: 3 },
        { rarity: 'Legendary', preset: 'S13', cost: 4 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D01', cost: 1 },
        { rarity: 'Rare', preset: 'D05', cost: 2 },
        { rarity: 'Epic', preset: 'D03', cost: 3 },
        { rarity: 'Legendary', preset: 'D09', cost: 4 },
      ],
    },
  },
  {
    key: 'MARCUS',
    display: '마커스',
    theme: 'Tactical',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A02', cost: 2 },
        { rarity: 'Rare', preset: 'A09', cost: 2 },
        { rarity: 'Epic', preset: 'A05', cost: 3 },
        { rarity: 'Legendary', preset: 'A13', cost: 4 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H03', cost: 3 },
        { rarity: 'Rare', preset: 'H11', cost: 3 },
        { rarity: 'Epic', preset: 'H10', cost: 3 },
        { rarity: 'Legendary', preset: 'H09', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S05', cost: 2 },
        { rarity: 'Rare', preset: 'S07', cost: 2 },
        { rarity: 'Epic', preset: 'S16', cost: 3 },
        { rarity: 'Legendary', preset: 'S10', cost: 4 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D02', cost: 2 },
        { rarity: 'Rare', preset: 'D11', cost: 2 },
        { rarity: 'Epic', preset: 'D12', cost: 3 },
        { rarity: 'Legendary', preset: 'D04', cost: 4 },
      ],
    },
  },
  {
    key: 'MIRA',
    display: '미라',
    theme: 'Shadow',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A14', cost: 1 },
        { rarity: 'Rare', preset: 'A05', cost: 2 },
        { rarity: 'Epic', preset: 'A07', cost: 3 },
        { rarity: 'Legendary', preset: 'A10', cost: 4 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H02', cost: 2 },
        { rarity: 'Rare', preset: 'H08', cost: 2 },
        { rarity: 'Epic', preset: 'H13', cost: 3 },
        { rarity: 'Legendary', preset: 'H07', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S01', cost: 1 },
        { rarity: 'Rare', preset: 'S13', cost: 2 },
        { rarity: 'Epic', preset: 'S17', cost: 3 },
        { rarity: 'Legendary', preset: 'S19', cost: 4 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D02', cost: 2 },
        { rarity: 'Rare', preset: 'D08', cost: 2 },
        { rarity: 'Epic', preset: 'D11', cost: 3 },
        { rarity: 'Legendary', preset: 'D06', cost: 4 },
      ],
    },
  },
  {
    key: 'SERAPHINA',
    display: '세라피나',
    theme: 'Shadow',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A05', cost: 2 },
        { rarity: 'Rare', preset: 'A07', cost: 3 },
        { rarity: 'Epic', preset: 'A10', cost: 3 },
        { rarity: 'Legendary', preset: 'A04', cost: 4 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H01', cost: 1 },
        { rarity: 'Rare', preset: 'H08', cost: 2 },
        { rarity: 'Epic', preset: 'H05', cost: 3 },
        { rarity: 'Legendary', preset: 'H04', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S05', cost: 2 },
        { rarity: 'Rare', preset: 'S17', cost: 3 },
        { rarity: 'Epic', preset: 'S10', cost: 4 },
        { rarity: 'Legendary', preset: 'S18', cost: 4 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D01', cost: 1 },
        { rarity: 'Rare', preset: 'D08', cost: 2 },
        { rarity: 'Epic', preset: 'D05', cost: 3 },
        { rarity: 'Legendary', preset: 'D10', cost: 4 },
      ],
    },
  },
  {
    key: 'SERAPHINE',
    display: '세라핀',
    theme: 'Light',
    assignments: {
      Attack: [
        { rarity: 'Normal', preset: 'A02', cost: 2 },
        { rarity: 'Rare', preset: 'A11', cost: 3 },
        { rarity: 'Epic', preset: 'A03', cost: 3 },
        { rarity: 'Legendary', preset: 'A15', cost: 3 },
      ],
      Heal: [
        { rarity: 'Normal', preset: 'H01', cost: 1 },
        { rarity: 'Rare', preset: 'H05', cost: 2 },
        { rarity: 'Epic', preset: 'H06', cost: 3 },
        { rarity: 'Legendary', preset: 'H12', cost: 4 },
      ],
      Special: [
        { rarity: 'Normal', preset: 'S03', cost: 2 },
        { rarity: 'Rare', preset: 'S15', cost: 3 },
        { rarity: 'Epic', preset: 'S05', cost: 3 },
        { rarity: 'Legendary', preset: 'S20', cost: 4 },
      ],
      Defense: [
        { rarity: 'Normal', preset: 'D01', cost: 1 },
        { rarity: 'Rare', preset: 'D04', cost: 3 },
        { rarity: 'Epic', preset: 'D10', cost: 3 },
        { rarity: 'Legendary', preset: 'D07', cost: 4 },
      ],
    },
  },
];

const bonusCards = [
  {
    id: 'ATT_SERAPHINA_EP_209',
    preset: 'A05',
    type: 'Attack',
    rarity: 'Epic',
    cost: 2,
    displayName: '혈월의 일격 (특수)',
    tags: ['Shadow'],
    keywords: ['Bleed'],
  },
  {
    id: 'DEF_LUCIAN_RA_210',
    preset: 'D05',
    type: 'Defense',
    rarity: 'Rare',
    cost: 2,
    displayName: '반응 장갑 전개 (특수)',
    tags: ['Metal'],
    keywords: ['Reactive'],
  },
  {
    id: 'HEAL_IRIS_RA_211',
    preset: 'H05',
    type: 'Heal',
    rarity: 'Rare',
    cost: 2,
    displayName: '빛의 넘침 (특수)',
    tags: ['Light'],
    keywords: ['Regen'],
  },
  {
    id: 'SPC_MARCUS_EP_212',
    preset: 'S05',
    type: 'Special',
    rarity: 'Epic',
    cost: 2,
    displayName: '전술 시계 (특수)',
    tags: ['Tactical'],
    keywords: ['Tempo'],
  },
];

function buildCard(charIndex, char, type, assignment, rarity) {
  const preset = effectPresets[assignment.preset];
  if (!preset) {
    throw new Error(`Preset ${assignment.preset} not defined`);
  }
  const startNumber = charIndex * 16;
  const offset = typeOffsets[type][rarity];
  const cardNumber = startNumber + offset + 1;
  const idNumber = String(cardNumber).padStart(3, '0');
  const id = `${typeCodes[type]}_${char.key}_${rarityCodes[rarity]}_${idNumber}`;
  const effects = preset.effects(assignment);
  const card = {
    id,
    name: preset.name,
    type,
    rarity,
    cost: assignment.cost ?? 0,
    effects,
    tags: Array.from(new Set([char.theme, ...(preset.tags || [])])),
    keywords: Array.from(new Set(preset.keywords || [])),
    effectText: preset.effectText,
    levelCurve: preset.levelCurve ? deepClone(preset.levelCurve) : undefined,
    vfxKey: preset.vfx,
    sfxKey: preset.sfx,
    version: 1,
  };
  return card;
}

function buildBonusCard(entry) {
  const preset = effectPresets[entry.preset];
  if (!preset) throw new Error(`Preset ${entry.preset} missing for bonus`);
  return {
    id: entry.id,
    name: entry.displayName || preset.name,
    type: entry.type,
    rarity: entry.rarity,
    cost: entry.cost,
    effects: preset.effects(entry),
    tags: Array.from(new Set([...(entry.tags || []), ...(preset.tags || [])])),
    keywords: Array.from(new Set([...(entry.keywords || []), ...(preset.keywords || [])])),
    effectText: preset.effectText,
    levelCurve: preset.levelCurve ? deepClone(preset.levelCurve) : undefined,
    vfxKey: preset.vfx,
    sfxKey: preset.sfx,
    version: 1,
  };
}

function generateCards() {
  const cards = [];
  characters.forEach((char, index) => {
    ['Attack', 'Heal', 'Special', 'Defense'].forEach(type => {
      const assignments = char.assignments[type];
      rarityOrder.forEach((rarity, i) => {
        const assignment = assignments[i];
        if (!assignment || assignment.rarity !== rarity) {
          throw new Error(`Assignment mismatch for ${char.key} ${type} ${rarity}`);
        }
        cards.push(buildCard(index, char, type, assignment, rarity));
      });
    });
  });
  bonusCards.forEach(entry => {
    cards.push(buildBonusCard(entry));
  });
  return cards;
}

function writeFile(targetPath, cards) {
  const dir = path.dirname(targetPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(targetPath, `${JSON.stringify(cards, null, 2)}\n`, 'utf8');
}

function main() {
  const cards = generateCards();
  const publicPath = path.join(__dirname, '..', 'web', 'public', 'data', 'cards.json');
  const distPath = path.join(__dirname, '..', 'web', 'dist', 'data', 'cards.json');
  writeFile(publicPath, cards);
  writeFile(distPath, cards);
  console.log(`Generated ${cards.length} cards.`);
}

main();

